# Name of the site, used in title (required)
title: Example site

# Full URL of the site with trailing slash (required)
url: http://example.com/

# Meta description (optional but recommended)
description: Description of an example site made with Stagger.

# Favicon (optional but recommended)
icon: favicon.png

# Site language (optional but recommended)
lang: en

# Main image (optional, used in social media metadata)
image: stagger.png

# Additional metadata
meta: {
  # Open Graph (Facebook)
  og: true,
  # Twitter Card
  twitter: false
}

# CSS-files
css: [
  spectre.css,
  spectre-icons.css,
  hljs-default.css,
  style.css
]

# JS-files
js: [
  app.js
]

# Menu
menu: [
  home,
  about,
  blog
]

# CSS-classes for HTML elements
classes: {
  table: table
}
